[logger]
version = 1
    [logger.formatters]
        [logger.formatters.standard]
        format = """\
            Level: [{levelname}] | \
            Thread: [{threadName}:{thread}] | \
            Process: [{processName}:{process}] | \
            Logger: [{name}:{funcName}:{lineno}] | \
            Log: [{message}] | \
            Context: [{args}]"""
        style = '{'
    [logger.handlers]
        [logger.handlers.console]
        level = 'DEBUG'
        formatter = 'standard'
        class = 'logging.StreamHandler'
        stream ='ext://sys.stdout'
    [logger.loggers]
        [logger.loggers.app]
        handlers = ['console']
        level = 'DEBUG'
